### ISSUE TITLE
minecraft 1.12.2 error loading candyworld 1.1.4 

### ISSUE THREAD

**Issue by marrti** [ochotonida/candymod#30]
hello,
that error ocurrs if i start minecraft 1.12.2 :

et.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Candy World (candymod)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 23, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at com.ochotonida.candymod.world.dimension.Dimension.init(Dimension.java:14)
	at com.ochotonida.candymod.proxy.CommonProxy.preInit(CommonProxy.java:20)
	at com.ochotonida.candymod.proxy.ClientProxy.preInit(ClientProxy.java:44)
	at com.ochotonida.candymod.CandyMod.preInit(CandyMod.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ochotonida** [comment]
You already have a mod that uses the same dimension ID as this mod, you can change it in the config to a different value

**Comment by marrti** [comment]
hello thank you for your answer ! Can you read what mod that is that causes that problem and how can i change it to a different value ? Thanks a lot for your help.
regards, marrti

**Comment by florensie** [comment]
@marrti
1. No, it's not in the log
2. Change it in the config file (.Minecraft/config/...)

**Comment by marrti** [comment]
thank you and i dont know witch mod is causes that i have looked at all mod's but did not find a mod with the same id ! But i've changed it anyway thank you for your help!

**Comment by marrti** [comment]
hello here i am again the id' not working ! the originall id was 23 i chanced to 1 ,10, 8,71,89,64,24, but noting works who can i see what id's is registered ?
thank you for yor help here the minecraft error log : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.3.jar)
  wings (wings-1.1.3-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 10/12/19 1:26 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Candy World (candymod)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 1, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at com.ochotonida.candymod.world.dimension.Dimension.init(Dimension.java:14)
	at com.ochotonida.candymod.proxy.CommonProxy.preInit(CommonProxy.java:20)
	at com.ochotonida.candymod.proxy.ClientProxy.preInit(ClientProxy.java:44)
	at com.ochotonida.candymod.CandyMod.preInit(CandyMod.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 621087088 bytes (592 MB) / 1526558720 bytes (1455 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 50 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version                | Source                                             | Signature                                |
	|:----- |:---------------------- |:---------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft              | 1.12.2                 | minecraft.jar                                      | None                                     |
	| LCH   | mcp                    | 9.42                   | minecraft.jar                                      | None                                     |
	| LCH   | FML                    | 8.0.99.99              | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | forge                  | 14.23.5.2847           | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | micdoodlecore          |                        | minecraft.jar                                      | None                                     |
	| LCH   | securitycraft          | v1.8.12.1              | [1.12.2]+SecurityCraft+v1.8.12.1.jar               | None                                     |
	| LCH   | craftstudioapi         | 1.0.0                  | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCH   | twilightforest         | 3.8.689                | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
	| LCH   | animania               | 1.6.2                  | animania-1.12.2-1.6.2.jar                          | None                                     |
	| LCH   | any_dimension_mod      | 1.3.4                  | any_dimension_mod_v1.3.4.jar                       | None                                     |
	| LCH   | blocklings             | 6.0.1                  | Blocklings+6.0.1+-+1.12.2.jar                      | None                                     |
	| LCH   | capsule                | 1.12.2-3.1.69          | Capsule-1.12.2-3.1.69.jar                          | None                                     |
	| LCH   | car                    | 1.2.12                 | car-1.12.2-1.2.12.jar                              | None                                     |
	| LCH   | codechickenlib         | 3.2.2.353              | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ptrmodellib            | 1.0.0                  | Decocraft-2.5.1_1.12.2.jar                         | None                                     |
	| LCH   | props                  | 2.5.1                  | Decocraft-2.5.1_1.12.2.jar                         | None                                     |
	| LCH   | eyemod                 | 1.1.0                  | EyeMod-Mod-1.12.2.jar                              | None                                     |
	| LCH   | galacticraftcore       | 4.0.2.190              | GalacticraftCore-1.12.2-4.0.2.190.jar              | None                                     |
	| LCH   | galacticraftplanets    | 4.0.2.190              | Galacticraft-Planets-1.12.2-4.0.2.190.jar          | None                                     |
	| LCH   | lucraftcore            | 1.12.2-2.4.3           | LucraftCore-1.12.2-2.4.3.jar                       | None                                     |
	| LCH   | heroesexpansion        | 1.12.2-1.3.3           | HeroesExpansion-1.12.2-1.3.3.jar                   | None                                     |
	| LCH   | llibrary               | 1.7.18                 | llibrary-1.7.18-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire             | 1.7.1                  | iceandfire-1.7.1-1.12.2.jar                        | None                                     |
	| LCH   | ichunutil              | 7.1.4                  | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
	| LCH   | imsm                   | 1.12                   | Instant-Massive-Structures-Mod-1.12.jar            | None                                     |
	| LCH   | inventorypets          | 2.0.1                  | inventorypets-1.12-2.0.1.jar                       | None                                     |
	| LCH   | jei                    | 4.13.1.225             | jei_1.12.2-4.13.1.225.jar                          | None                                     |
	| LCH   | journeymap             | 1.12-5.4.9             | journeymap-1.12-5.4.9.jar                          | None                                     |
	| LCH   | libvulpes              | 0.3.0.-44              | LibVulpes-1.12.2-0.3.0-44-universal.jar            | None                                     |
	| LCH   | lucky                  | 7.5.0                  | LuckyBlock_1-12_v7-5-0.zip                         | None                                     |
	| LCH   | millenaire             | MillÃ©naire 7.2.0       | millenaire-1.12.2-7.2.0.jar                        | None                                     |
	| LCH   | mob_grinding_utils     | 0.3.5                  | MobGrindingUtils-1.12.jar                          | None                                     |
	| LCH   | moreplayermodels       | 1.12.2                 | More-Player-Models-Mod-1.12.2.jar                  | None                                     |
	| LCH   | morph                  | 7.1.2                  | Morph-1.12.2.jar                                   | None                                     |
	| LCH   | cdm                    | 0.4.1                  | MrCrayfishs-Device-Mod-1.12.2.jar                  | None                                     |
	| LCH   | cfm                    | 6.2.0                  | MrCrayfishs-Furniture-Mod-1.12.2.jar               | None                                     |
	| LCH   | nei                    | 2.4.2                  | NotEnoughItems-1.12.2-2.4.2.240-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | pizzacraft             | 1.4.1                  | PizzaCraft-1.12.2-1.4.2.jar                        | None                                     |
	| LCH   | redstoneflux           | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar            | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| LCH   | scannable              | 1.6.3.24               | Scannable-MC1.12.2-1.6.3.24.jar                    | None                                     |
	| LCH   | thutcore               | 5.19.9                 | thutcore-1.12.2-5.19.9.jar                         | None                                     |
	| LCH   | thutcore_compat        | 1.0                    | thutcore-1.12.2-5.19.9.jar                         | None                                     |
	| LCH   | thuttech               | 6.1.5                  | thuttech-1.12.2-6.1.5.jar                          | None                                     |
	| LCH   | vampirism              | 1.5.0                  | Vampirism-1.12.2-1.5.0.jar                         | None                                     |
	| LCH   | teamlapen-lib          | 1.5.0                  | Vampirism-1.12.2-1.5.0.jar                         | None                                     |
	| LCH   | vampirism_integrations | vampirism_integrations | VampirismIntegrations-1.12.2-1.1.0.jar             | None                                     |
	| LCH   | wings                  | 1.1.3                  | wings-1.1.3-1.12.2.jar                             | None                                     |
	| LCE   | candymod               | 1.1.4                  | candyworld-1.1.4.jar                               | None                                     |
	| UD    | bauble_wings           | 1.0.0                  | wings-1.1.3-1.12.2.jar                             | None                                     |
	| UD    | mobends_wings          | 1.0.0                  | wings-1.1.3-1.12.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.3.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
wings (wings-1.1.3-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 660/PCIe/SSE2'

**Comment by florensie** [comment]
Pick something really random and not too low.

**Comment by marrti** [comment]
i have done that but not working! i can choose from up to 8 to 79 ! 1-7 is not accepted and from 80 up is not accepted too ! 
thank you for your help and effort.
regards,
